### ISSUE TITLE
UNABLE TO RUN PROJECT

### ISSUE THREAD

**Issue by benemanuel** [Limezy/Unbound2Athens#1]
Using python Python 3.10.1 all attempts on different books come with same results.

python Unbound2Athens.py
Traceback (most recent call last):
  File "C:\GitHub\Unbound2Athens\Unbound2Athens.py", line 206, in <module>
    bibleBuilder("LXX","lxx_a_unaccented","lxx_a_unaccented",True)
  File "C:\GitHub\Unbound2Athens\Unbound2Athens.py", line 178, in bibleBuilder
    createBookBlock(book, title)
  File "C:\GitHub\Unbound2Athens\Unbound2Athens.py", line 74, in createBookBlock
    writeLine(bookBlock,createStringDatom("9555"+bookTuple[0],bookTitle))
  File "C:\GitHub\Unbound2Athens\Unbound2Athens.py", line 54, in writeLine
    f.write(line+"\n")
  File "C:\Python310\lib\encodings\cp1255.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4d6' in position 25: character maps to <undefined>

**Comment by Limezy** [comment]
Hi @benemanuel !
This is not a project I currently work on. If I remember well I was using python 2.7.
However I have some bibles available for Athens format. Is that what you would like to get in the end ?

**Comment by benemanuel** [comment]
I will try with 2.7, Got my own Bible to process.

**Comment by Limezy** [comment]
https://stackoverflow.com/questions/62656579/why-im-getting-unicodeencodeerror-charmap-codec-cant-encode-character-u2
The problem seems to be linked with the fact that you use Windows

**Comment by Limezy** [comment]
Hi @benemanuel did you manage to run the script ?
Are you using Athens to study the Bible ?

**Comment by benemanuel** [comment]
I did succeed getting the script to run. As for using Athens, it seems too cumbersome to me for Bible studies, especially that I am not familiar with it's interface enough.

**Comment by Limezy** [comment]
On my side I'm using Obsidian, with quite a great success
You can have a look at the Anthropologie Biblique repositories as most of my bible scripts are meant to be used with Obsidian
